# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b817ac8cf5bc7f145ebe044d3cf53fb"
name = "novaalab order protection"
handle = "novaalab-order-protection"
application_url = "https://novaalab.articmaze.dev/"
embedded = true

[build]
dev_store_url = "novaalab-app-test.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [ "https://novaalab.articmaze.dev/public/authenticate" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
